serverAddr = "8.163.93.151"
serverPort = 7000
auth.method = "token"
auth.token = "${FRP_AUTH_TOKEN}"

[[proxies]]
name = "target-b-ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 60022

[[proxies]]
name = "target-b-rdp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 60023

[[proxies]]
name = "target-b-rdp-udp"
type = "udp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 60023

[[proxies]]
name = "target-b-sunshine-https"
type = "tcp"
localIP = "127.0.0.1"
localPort = 47984
remotePort = 47984

[[proxies]]
name = "target-b-sunshine-http"
type = "tcp"
localIP = "127.0.0.1"
localPort = 47989
remotePort = 47989

[[proxies]]
name = "target-b-sunshine-rtsp-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 48010
remotePort = 48010

[[proxies]]
name = "target-b-sunshine-video"
type = "udp"
localIP = "127.0.0.1"
localPort = 47998
remotePort = 47998

[[proxies]]
name = "target-b-sunshine-control"
type = "udp"
localIP = "127.0.0.1"
localPort = 47999
remotePort = 47999

[[proxies]]
name = "target-b-sunshine-audio"
type = "udp"
localIP = "127.0.0.1"
localPort = 48000
remotePort = 48000

[[proxies]]
name = "target-b-sunshine-mic"
type = "udp"
localIP = "127.0.0.1"
localPort = 48002
remotePort = 48002

[[proxies]]
name = "target-b-sunshine-rtsp-udp"
type = "udp"
localIP = "127.0.0.1"
localPort = 48010
remotePort = 48010
