"use client"

export { DashboardPage as DashboardPageClient } from "@/features/dashboard/DashboardPage"
export { UsersPage as UsersPageClient } from "@/features/users/UsersPage"
export { LotteryTypesPage as LotteryTypesPageClient } from "@/features/lottery-types/LotteryTypesPage"
export { DrawsPage as DrawsPageClient } from "@/features/draws/DrawsPage"
export { SitesPage as SitesPageClient } from "@/features/sites/SitesPage"
export { NumbersPage as NumbersPageClient } from "@/features/numbers/NumbersPage"
export { SiteDataPage as SiteDataPageClient } from "@/features/site-data/SiteDataPage"
export { PredictionModulesPage as PredictionModulesPageClient } from "@/features/prediction-modules/PredictionModulesPage"
